banking/analyze/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index')
]

banking/banking/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^analyze/', include('analyze.urls')),
    url(r'^memeconomy/', include('memeconomy.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

banking/memeconomy/urls.py
from django.conf.urls import url

from . import views

app_name = 'memeconomy'
urlpatterns = [
	url(r'^profile$', views.profile, name='profile'),
	url(r'^create/$', views.create, name='create'),
	url(r'^(?P<meme_id>[a-zA-Z0-9]+)/buy/$', views.buy, name='buy'),
	url(r'^(?P<meme_id>[a-zA-Z0-9]+)/sell/$', views.sell, name='sell'),
	url(r'^(?P<meme_id>[a-zA-Z0-9]+)/view/$', views.view, name='view'),
	url(r'^$', views.index, name='index')
]

banking/analyze/models.py
from django.db import models

# Create your models here.

banking/memeconomy/models.py
from django.db import models
from django.contrib.auth.models import User

class Trader(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	customer_id = models.CharField(max_length=200)
	account_ids = models.CharField(max_length=200)

banking/memeconomy/forms.py
from django import forms

class MemeForm(forms.Form):
	memepage = forms.CharField(label="Know your meme page", max_length=100)
	categories = forms.CharField(label="Comma-separated meme categories", max_length=200)

banking/analyze/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'analyze/index.html', {})

banking/memeconomy/views.py
from django.shortcuts import render, redirect
from . import api
from .forms import *
from .models import *

# Create your views here.
def index(request):
	return render(request, 'memeconomy/index.html', {})

def profile(request):
	if request.user.id == None:
		return render(request, 'memeconomy/index.html', {'error': 'Please login.'})
	
	trader = Trader.get(user=request.user.id)
	if trader == None:
		form = CustomerForm()
		return render(request, 'memeconomy/profile.html', {'form':form})


	if request.method == 'POST':	
		form = CustomerForm(request.POST)
		if form.is_valid():
			# TODO: do some input validation
			resp = api.createMerchant(form.cleaned_data["memepage"], form.cleaned_data["categories"].split(','))
			if resp != None:
				return redirect('http://localhost:8000/memeconomy/'+str(resp["objectCreated"]["_id"])+'/view')
			return render(request, 'memeconomy/index.html', {'error': 'Error creating meme'})

			trader = Trader.get(user=request.user.id)
			if trader == None:
				customer = createCustomer(first_name, last_name, street_number, street_name, city, state, zipCode)["objectCreated"]
				account = createCustomerAccount(customer_id, type, nickname, rewards, balance, account_number=None)["objectCreated"]

				customer = api.createCustomer()
				account_id = api.getCustomerAccounts(customer_id)
				trader = Trader()
				trader.save()


	form = CustomerForm()


	return render(request, 'memeconomy/profile.html', {'form':form})

def create(request):
	if request.user.id == None:
		return render(request, 'memeconomy/index.html', {'error': 'Please login.'})

	if request.method == 'POST':	
		form = MemeForm(request.POST)
		if form.is_valid():
			# TODO: do some input validation
			resp = api.createMerchant(form.cleaned_data["memepage"], form.cleaned_data["categories"].split(','))
			if resp != None:
				return redirect('http://localhost:8000/memeconomy/'+str(resp["objectCreated"]["_id"])+'/view')
			return render(request, 'memeconomy/index.html', {'error': 'Error creating meme'})

	form = MemeForm()
	return render(request, 'memeconomy/makememe.html', {'form':form})

def buy(request, meme_id):
	if request.user.id == None:
		return render(request, 'memeconomy/index.html', {'error': 'Please login.'})

	return redirect('view', meme_id)

def sell(request, meme_id):
	if request.user.id == None:
		return render(request, 'memeconomy/index.html', {'error': 'Please login.'})

	return redirect('view', meme_id)

def view(request, meme_id):
	if request.user.id == None:
		return render(request, 'memeconomy/index.html', {'error': 'Please login.'})

	merchant = api.getMerchant(meme_id)
	if merchant == None:
		return render(request, 'memeconomy/index.html', {'error': 'No such meme.'})

	purchases = api.getMerchantPurchases(meme_id)
	if purchases == None:
		return render(request, 'memeconomy/index.html', {'error': 'Could not retrieve meme history.'})

	return render(request, 'memeconomy/meme.html', {'merchant': merchant, 'purchases': purchases})

banking/analyze/templates/analyze/index.html
index.html

banking/memeconomy/templates/memeconomy/index.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<p class="error">{{error}}</p>
{% endif %}


<p>test</p>
<a href="/accounts/login">Login</a>

{% endblock %}

banking/memeconomy/templates/memeconomy/makememe.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<p class="error">{{error}}</p>
{% endif %}


<form action="{% url 'memeconomy:create' %}" method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="Submit">
</form>

<script type="text/javascript">
	// setup bootstrap formatting
	function mergejQueryObjects(arrayOfJqueryObjects) {
        return $($.map(arrayOfJqueryObjects, function (el) {
            return el.get();
        }));
    }
	$('form label').each(function() {
		var next, elements = [$(this)];
		do {
			if(next) {
				next = $(next[0]).next();
			} else {
				next = $(this).next();
			}
			elements.push($(next));
		} while(next[0].nodeName != 'SPAN');

		mergejQueryObjects(elements).wrapAll('<div class="form-group">');
	});
</script>

{% endblock %}

banking/memeconomy/templates/memeconomy/meme.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<p class="error">{{error}}</p>
{% endif %}




{{merchant}}
{{purchases}}


{% endblock %}

banking/memeconomy/templates/memeconomy/profile.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
<p class="error">{{error}}</p>
{% endif %}


<p>profile</p>

{{trader}}

{% endblock %}

banking/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>MEMEconomy</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>


<body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>